# Generated by Django 3.2.12 on 2022-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=50)),
                ('report_function', models.CharField(max_length=150)),
            ],
        ),
    ]
